### ISSUE TITLE
writing `&[]` to a sampling port yields an error

### ISSUE THREAD

**Issue by wucke13** [DLR-FT/a653rs-linux#86]
I think its valid to write an empty message to a sampling port, to clear all data that was in it before.

**Comment by florianhartung** [comment]
`ARINC653 P1 3.6.2.1.2` actually defines that writing an empty buffer should result in `InvalidParam` being returned. This is already implemented correctly.

However when trying to write an empty buffer, `a653rs::apex::types::Error::WriteError` is falsely returned.
It turns out that the check whether a buffer is empty is done in the `a653rs` crate itself, when validating the buffer size (see [here](https://github.com/DLR-FT/a653rs/blob/69389abb46811d2b3c2bef8f0055926754785a78/src/apex/types.rs#L225)).

**Comment by wucke13** [comment]
closed via https://github.com/DLR-FT/a653rs/issues/37
